### ISSUE TITLE
Option to pass the `nonempty` parameter

### ISSUE THREAD

**Issue by callegar** [rene/nlinkfs#1]
Is there an option to pass fuse the nonempty param to mount on a directory that is not empty?

**Comment by rene** [comment]
@callegar , yes, you can pass any fuse option after first argument (source dir, make sure to use the full path). Like this: 

```bash
nlinkfs sourcedir mountdir -o nonempty
```

**Comment by callegar** [comment]
OK, that is clear now. I was trying to pass the option as the first argument...
