### ISSUE TITLE
Creating temporary files fails on nlinkfs

### ISSUE THREAD

**Issue by callegar** [rene/nlinkfs#4]
This is very evident using `git`.

To reproduce:
1. create a directory in an nlinkfs filesystem;
2. cd into it
3. `git init`
4. `touch foo`
5. `git add foo`

The above fails

**Comment by rene** [comment]
Issue confirmed: strace shows an error on openat():

openat(AT_FDCWD, ".git/objects/e6/tmp_obj_oAP5xh", O_RDWR|O_CREAT|O_EXCL, 0444) = -1 EPERM (Operation not permitted)

I'll take a look...

**Comment by rene** [comment]
@callegar , this issue is now fixed by commit 2f78fc262398b869b1f40dc1549d33e63eaac2a5, could you please confirm if it works for you as well?

**Comment by callegar** [comment]
Confirmed
