### ISSUE TITLE
nlinkfs gets confused if both `file` and `file.LNK` appear in the source dir

### ISSUE THREAD

**Issue by callegar** [rene/nlinkfs#7]
If the source dir used for `nlinkfs` is also accessed directly, it may happen to mistakenly put a file there when there is already a corresponding `.LNK` file.

In this case, `nlinkfs` gets badly confused and shows the same item twice (with the same name) in the mounted directory.

I suggest that in this case in the mounted filesystem you see the `.LNK` file as is, rather than translated into a symlink.

**Comment by rene** [comment]
This issue is now solved by the following commit: https://github.com/rene/nlinkfs/commit/e292ba8f67eb0c5b2b303ddd1fe5c72e908461d7

@callegar , I didn't test too much, let me know if you find some problem.
